site_name: IncluCheck
site_url: https://unbihc2025-1.github.io/IHC-2025.1-Grupo08/
repo_url: https://github.com/UnBIHC2025-1/IHC-2025.1-Grupo08
repo_name: IHC-2025.1-Grupo08

use_directory_urls: false

nav:
  - Início - IncluCheck: "index.md"
  - Desenvolvimento Web:
      - Desenvolvimento: "devWeb/non_text_content.md"
  - Design:
      - Design: "design/design.md"
  - Geração de Conteúdo:
      - Conteúdo: "geracaoConteudo/conteudo.md"
  - Gestão de Projetos:
      - Gestão de Projetos: "gestaoProjeto/gestaoProjeto.md"
  - Ferramentas:
      - Ferramentas de Acessibilidade: "tools/ferramentas.md"
  - Guia de Acessibilidade:
      - Guia de Acessibilidade: "guiaAcessibilidade/guiaAcessibilidade.md"

theme:
  name: material
  locale: pt_BR
  logo: imagens/logo-incluchek.png
  favicon: imagens/logo-incluchek.png
  custom_dir: docs/overrides
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight
    - search.suggest
    - toc.integrate
    - navigation.top
    - navigation.expand

  palette:
    - scheme: default
      primary: green
      accent: light blue
      toggle:
        icon: material/lightbulb
        name: Modo escuro
    - scheme: slate
      primary: green
      accent: light blue
      toggle:
        icon: material/lightbulb-outline
        name: Modo claro
markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - js/progresso-checkbox.js
  - js/back-to-top.js
